-- CV content schema (issue #11), based on schema.md from issue #10.
-- CV item ordering is derived at query time from tag relevance to the
-- selected role_profile (not stored sort_order columns).

-- ---------------------------------------------------------------------------
-- Core identity
-- ---------------------------------------------------------------------------

CREATE TABLE profile (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(255) NOT NULL,
    headline   VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(64),
    location   VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contact_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    label      VARCHAR(255) NOT NULL,
    url        VARCHAR(2048) NOT NULL
);

CREATE INDEX idx_contact_link_profile ON contact_link (profile_id);

-- ---------------------------------------------------------------------------
-- Role awareness
-- ---------------------------------------------------------------------------

CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE role_profile (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(128) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    type       VARCHAR(32) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_role_profile_type CHECK (type IN ('GENERAL', 'PERMANENT', 'VACANCY'))
);

-- At most one GENERAL role profile (default / hidden profile).
CREATE UNIQUE INDEX uq_role_profile_one_general
    ON role_profile (type)
    WHERE type = 'GENERAL';

CREATE TABLE role_profile_tag (
    role_profile_id BIGINT NOT NULL REFERENCES role_profile (id) ON DELETE CASCADE,
    tag_id          BIGINT NOT NULL REFERENCES tag (id) ON DELETE RESTRICT,
    weight          NUMERIC(4, 3) NOT NULL,
    PRIMARY KEY (role_profile_id, tag_id),
    CONSTRAINT chk_role_profile_tag_weight CHECK (weight >= 0 AND weight <= 1)
);

CREATE TABLE introduction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id      BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    role_profile_id BIGINT NOT NULL UNIQUE REFERENCES role_profile (id) ON DELETE RESTRICT,
    content         TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Experience
-- ---------------------------------------------------------------------------

CREATE TABLE experience (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    company    VARCHAR(255) NOT NULL,
    title      VARCHAR(255) NOT NULL,
    location   VARCHAR(255),
    start_date DATE NOT NULL,
    end_date   DATE,
    CONSTRAINT chk_experience_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE experience_bullet (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id BIGINT NOT NULL REFERENCES experience (id) ON DELETE CASCADE,
    content       TEXT NOT NULL
);

CREATE TABLE experience_bullet_tag (
    experience_bullet_id BIGINT NOT NULL REFERENCES experience_bullet (id) ON DELETE CASCADE,
    tag_id               BIGINT NOT NULL REFERENCES tag (id) ON DELETE RESTRICT,
    PRIMARY KEY (experience_bullet_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Education
-- ---------------------------------------------------------------------------

CREATE TABLE education (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    institution VARCHAR(255) NOT NULL,
    degree      VARCHAR(255),
    field       VARCHAR(255),
    start_date  DATE,
    end_date    DATE,
    CONSTRAINT chk_education_dates CHECK (
        start_date IS NULL OR end_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE education_bullet (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_id BIGINT NOT NULL REFERENCES education (id) ON DELETE CASCADE,
    content      TEXT NOT NULL
);

CREATE TABLE education_bullet_tag (
    education_bullet_id BIGINT NOT NULL REFERENCES education_bullet (id) ON DELETE CASCADE,
    tag_id              BIGINT NOT NULL REFERENCES tag (id) ON DELETE RESTRICT,
    PRIMARY KEY (education_bullet_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Skills
-- ---------------------------------------------------------------------------

CREATE TABLE skill_category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    name       VARCHAR(255) NOT NULL
);

CREATE TABLE skill (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES skill_category (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL
);

CREATE TABLE skill_tag (
    skill_id BIGINT NOT NULL REFERENCES skill (id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES tag (id) ON DELETE RESTRICT,
    PRIMARY KEY (skill_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------------

CREATE TABLE project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    github_url  VARCHAR(2048),
    live_url    VARCHAR(2048)
);

CREATE TABLE project_bullet (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    content    TEXT NOT NULL
);

CREATE TABLE project_technology (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name       VARCHAR(255) NOT NULL
);

CREATE TABLE project_bullet_tag (
    project_bullet_id BIGINT NOT NULL REFERENCES project_bullet (id) ON DELETE CASCADE,
    tag_id            BIGINT NOT NULL REFERENCES tag (id) ON DELETE RESTRICT,
    PRIMARY KEY (project_bullet_id, tag_id)
);
